# -*- coding: utf-8 -*-
"""Скутилин КИ19-23Б

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vjVG24nurSfW5cdNlJQRxkqJeS8LLj8F
"""

s = 'Привет, Мир!'

print(s)

"""Скутилин Илья Юрьевич, КИ19-23Б"""